# Generated by Django 3.1.1 on 2020-11-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=8)),
                ('image', models.ImageField(default='default.jpg', upload_to='dog_pictures')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adoption.breed')),
            ],
        ),
    ]
