# Generated by Django 3.1.1 on 2020-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['age']},
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='type',
            new_name='breedType',
        ),
    ]
