# Generated by Django 3.1.1 on 2020-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_auto_20201119_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breedType',
            field=models.CharField(choices=[('terrier', 'Terrier'), ('akita', 'Akita'), ('bulldog', 'Bulldog'), ('rottweiler', 'Rottweiler'), ('pug', 'Pug'), ('mastiff', 'Mastiff'), ('akita', 'Akita'), ('akita', 'Akita'), ('akita', 'Akita'), ('akita', 'Akita'), ('akita', 'Akita')], default='terrier', max_length=100),
        ),
    ]
