# Generated by Django 3.1.1 on 2020-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_auto_20201119_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breedType',
            field=models.CharField(max_length=100),
        ),
    ]
